apiVersion: v2
<<<<<<< HEAD
appVersion: v2.10.3
=======
appVersion: v2.10.2
>>>>>>> origin/main
description: 'The Piraeus Operator manages software defined storage clusters using
  LINSTOR in Kubernetes. '
home: https://piraeus.io
icon: https://raw.githubusercontent.com/piraeusdatastore/piraeus/master/artwork/sandbox-artwork/icon/color.svg
keywords:
- storage
maintainers:
- name: Piraeus Datastore
  url: https://piraeus.io
name: piraeus
sources:
- https://github.com/piraeusdatastore/piraeus-operator
- https://github.com/piraeusdatastore/linstor-csi
- https://github.com/LINBIT/linstor-server
type: application
<<<<<<< HEAD
version: 2.10.3
=======
version: 2.10.2
>>>>>>> origin/main
